<?php
// upgrade_bios.php by Eduardo Bussien
// Run ONCE in your browser: http://localhost/olympus/sql/upgrade_bios.php
// Adds a `sources` column (if missing) and rewrites every character's full_bio
// with an expanded biography plus citations to ancient sources.
// Safe to run multiple times - uses UPDATE on existing rows.

require __DIR__ . '/db.php';

header('Content-Type: text/html; charset=utf-8');
echo "<pre style='font-family:monospace;font-size:13px;line-height:1.5;'>";

// 1. Add the sources column if it doesn't exist yet
$colCheck = $conn->query("SHOW COLUMNS FROM characters LIKE 'sources'");
if ($colCheck && $colCheck->num_rows === 0) {
    if ($conn->query("ALTER TABLE characters ADD COLUMN sources TEXT NULL AFTER full_bio")) {
        echo "[+] Added column `sources` to `characters`\n";
    } else {
        echo "[!] Failed to add column: " . $conn->error . "\n";
        exit;
    }
} else {
    echo "[=] Column `sources` already exists\n";
}

// 2. Expanded biographies + sources for every character
$updates = [
    // ======================== OLYMPIANS ========================
    'zeus' => [
        'bio' => "Zeus is the supreme deity of the Greek pantheon - sovereign of Mount Olympus, lord of the sky and of weather, and final guarantor of cosmic order. He is the youngest son of the Titans Cronus and Rhea, born in secret on Crete after his father had swallowed his elder siblings to forestall a prophecy. Rhea hid the infant in the Dictaean Cave, where the goat Amalthea suckled him and the Curetes drowned out his cries by clashing their spears against their shields.\n\nGrown to manhood, Zeus forced Cronus to disgorge the children he had consumed - Hestia, Demeter, Hera, Hades, and Poseidon - and led them in a ten-year war against the Titans known as the Titanomachy. Victorious, the brothers cast lots for the cosmos: Zeus took the heavens, Poseidon the sea, Hades the underworld, while the earth and Olympus were held in common. He further secured his rule by defeating the monstrous Typhon, the last and greatest challenger to divine order.\n\nZeus presides over justice, hospitality, oaths, and the sanctity of suppliants - yet he is also the most prolific lover in Greek myth, fathering Athena, Apollo, Artemis, Hermes, Dionysus, Heracles, Perseus, Helen, and many more. His thunderbolt, eagle, oak, and aegis are his enduring emblems, and the great sanctuary at Olympia, home of the Olympic Games, was the heart of his cult.",
        'sources' => "Hesiod, Theogony 453-506 (birth and infancy)\nHesiod, Theogony 617-735 (Titanomachy)\nHesiod, Theogony 820-880 (defeat of Typhon)\nHomer, Iliad, books 1, 8, 15 (sovereignty over the gods)\nApollodorus, Bibliotheca 1.1-1.2\nPausanias, Description of Greece 5.7-5.27 (sanctuary at Olympia)",
    ],
    'hera' => [
        'bio' => "Hera, daughter of Cronus and Rhea and queen of the gods, is the great divine patroness of marriage, legitimate childbirth, and the dignity of households. After Zeus freed her from her father, she became his sister and his wife; their wedding on Mount Ida or in the Garden of the Hesperides, depending on the source, was attended by every deity and even the earth produced golden apples in their honour.\n\nIn cult Hera was worshipped as Hera Teleia ('the Fulfilled'), the bride who completes the marriage, and her great temples at Argos, Samos, and Olympia made her one of the most powerful goddesses of the Greek world. Her sacred animals are the cow, the peacock, and the cuckoo; her attributes are the diadem, the scepter, and the pomegranate.\n\nMyth, however, remembers her chiefly through her jealousies. She persecuted the lovers and children of Zeus relentlessly - driving Io across the world in the form of a heifer, sending serpents to the cradle of the infant Heracles, and harassing him through his twelve labours. She supported the Achaeans at Troy in opposition to Zeus's favourites, championed Jason and the Argonauts against Pelias, and her hatred of Paris's judgment helped doom the city of Troy. For all her severity, Hera embodies divine queenship: regal, demanding, and inseparable from the institution of marriage itself.",
        'sources' => "Homer, Iliad 4.50-67; 14.153-353 (the deception of Zeus)\nHesiod, Theogony 921-923\nApollodorus, Bibliotheca 1.3.1, 2.4.8 (Heracles)\nPausanias, Description of Greece 2.17 (Heraion of Argos); 5.16 (Heraia at Olympia)\nOvid, Metamorphoses 1.583-746 (Io)",
    ],
    'poseidon' => [
        'bio' => "Poseidon, brother of Zeus and Hades, rules the sea, the rivers and springs, the horse, and the violent shaking of the earth. After the Titanomachy he received the waters as his portion, and from his palace beneath the Aegean he commands the storms, the tides, and the great sea monsters. The Cyclopes forged for him a trident with which he could split rocks, churn oceans, and rouse earthquakes - hence his epithet Ennosigaios, 'Earth-Shaker'.\n\nHe is credited in many traditions with creating the first horse, either by striking the earth with his trident or by pursuing Demeter in equine form. He fathered the winged Pegasus on Medusa, and his wife Amphitrite, a daughter of Nereus, bore him the merman Triton. He contended with Athena for the patronage of Athens, offering a saltwater spring while Athena gave the olive tree; the Athenians chose Athena, and Poseidon's resentment of the city is felt across myth.\n\nIn the Trojan War he fought alongside the Greeks, recalling Laomedon's refusal to pay him for building the city's walls. After the war he became Odysseus's great enemy: when the hero blinded Polyphemus, Poseidon's Cyclops son, the god prolonged his return for ten years. Sanctuaries at Sounion, Isthmia, and Helike were among his most prestigious cult centres.",
        'sources' => "Homer, Iliad 13.10-38; 15.184-219\nHomer, Odyssey 1.19-21; 9.526-535 (curse on Odysseus)\nHesiod, Theogony 278-281, 930-933\nApollodorus, Bibliotheca 1.2.1, 3.14.1\nPausanias, Description of Greece 2.1; 8.7 (Helike); 1.1 (Sounion)",
    ],
    'hades' => [
        'bio' => "Hades, eldest son of Cronus among the Olympian brothers (in Hesiod's reckoning) and lord of the unseen realm beneath the earth, rules the dead together with his queen Persephone. He is not a god of evil but of the inevitable: he sees that no shade escapes his kingdom and that the law of mortality remains absolute. His helm of darkness, forged by the Cyclopes, renders its wearer invisible - a gift he occasionally lends to gods and heroes such as Perseus.\n\nThe most famous myth of Hades is the abduction of Persephone, daughter of Demeter, whom he carried down to his palace through a chasm in the Nysian plain. The grief of Demeter brought famine to the earth, and Zeus brokered a compromise: Persephone, having tasted pomegranate seeds in the underworld, would spend a third of the year with Hades and the rest with her mother. The myth was the foundational story of the Eleusinian Mysteries, the most sacred initiation rite of ancient Greece.\n\nThe three-headed dog Cerberus guards his gates, the rivers Styx, Acheron, Cocytus, Phlegethon, and Lethe wind through his realm, and the judges Minos, Rhadamanthys, and Aeacus weigh the souls of the dead. Greeks called him Plouton ('the Wealthy One') in reference to the riches of the earth, and avoided speaking his true name aloud.",
        'sources' => "Homeric Hymn to Demeter 1-89, 334-470 (the abduction)\nHesiod, Theogony 311-312, 767-774\nHomer, Iliad 9.457; 15.187-193\nApollodorus, Bibliotheca 1.5.1; 2.5.12\nPlato, Cratylus 403a (the name Plouton)\nPausanias, Description of Greece 1.38 (Eleusis)",
    ],
    'demeter' => [
        'bio' => "Demeter is the goddess of grain, of the cultivated earth, and of the cycle of growth and harvest. Daughter of Cronus and Rhea, she taught mortals the art of agriculture and gave them the gift of bread, lifting humankind from the wild fare of acorns and roots into settled civilization. Her name means 'Earth Mother' or 'Grain Mother', and her attributes are the sheaf of wheat, the torch, and the cornucopia.\n\nThe central myth of Demeter is the loss of her daughter Persephone to Hades. While Persephone was gathering flowers in the meadow of Nysa, the earth opened and Hades carried her down into his realm. Demeter wandered the world in mourning, refusing to allow the grain to grow, until Zeus intervened and arranged Persephone's partial return. The annual reunion and parting of mother and daughter became the mythic basis for the seasons and for the Eleusinian Mysteries, which promised initiates a blessed afterlife.\n\nIn her grief Demeter also took refuge at Eleusis, where she was sheltered by King Celeus and his queen Metaneira and tried to grant immortality to their son Demophoon. When her ritual was interrupted she revealed herself in full divinity and instructed the Eleusinians in her sacred rites. Through Triptolemus, prince of Eleusis, she sent the gift of agriculture across the world.",
        'sources' => "Homeric Hymn to Demeter (full text)\nHesiod, Theogony 912-914, 969-974\nApollodorus, Bibliotheca 1.5\nOvid, Metamorphoses 5.341-571\nPausanias, Description of Greece 1.14, 1.38 (Eleusinian sanctuaries)",
    ],
    'athena' => [
        'bio' => "Athena, daughter of Zeus, is the goddess of wisdom, strategic warfare, weaving, and the protective patroness of cities and craftsmen. Her birth is one of the most striking in Greek myth: Zeus, having swallowed her pregnant mother Metis, suffered a splitting headache; Hephaestus cleaved his skull open with an axe, and Athena leapt forth fully grown and fully armed, with a shout that shook heaven and earth. Because she had no human conception or upbringing, she remained a virgin goddess, and was called Parthenos.\n\nHer most famous contest was with Poseidon for the patronage of Athens. The two gods offered gifts to the city: Poseidon a saltwater spring, Athena the olive tree, the source of food, oil, and wood. The Athenians chose Athena, and the city has carried her name ever since. The Parthenon on the Acropolis, built in the fifth century BCE, housed Phidias's gold and ivory statue of her and remains the most famous temple of the ancient world.\n\nAthena championed heroes through wisdom rather than brute force: she guided Perseus to slay Medusa (whose head she set upon her aegis), helped Heracles complete his labours, advised Bellerophon, and shielded Odysseus through the long return from Troy. She is the inventor of the loom and the bridle, and the giver of olive oil. The owl, the snake, and the olive are her sacred emblems.",
        'sources' => "Hesiod, Theogony 886-900, 924-926 (the swallowing of Metis and Athena's birth)\nHomeric Hymn to Athena (28)\nHomer, Iliad 5.733-863; Odyssey 1, 13, 22\nApollodorus, Bibliotheca 1.3.6; 2.4.2; 3.14.1\nOvid, Metamorphoses 6.1-145 (Arachne)\nPausanias, Description of Greece 1.24 (the Parthenon)",
    ],
    'apollo' => [
        'bio' => "Apollo, son of Zeus and the Titaness Leto, is the most many-sided of the Olympians. He is the god of light, prophecy, music, archery, healing, plague, the lyre, and the formal arts of order and proportion. Together with his twin sister Artemis, he was born on the floating island of Delos after Hera, in jealousy, forbade the earth to receive Leto. The newborn Apollo received nectar and ambrosia and went immediately on a journey to claim his oracular seat at Delphi, slaying the great serpent Python that had haunted the slopes of Mount Parnassus.\n\nThe oracle at Delphi was the most authoritative in the Greek world, where the Pythia, a priestess seated above a chasm, delivered Apollo's responses to kings, philosophers, and common citizens. Apollo also presided over the Pythian Games, and his great sanctuaries on Delos, at Didyma, and at Claros made him a god of pan-Hellenic identity. He is the leader of the Muses (Apollo Musagetes) and the inspirer of poets, prophets, and physicians; his son Asclepius brought medicine into the world.\n\nApollo's loves are often touched with sorrow. He pursued the nymph Daphne, who was transformed into a laurel tree to escape him; from then on the laurel was his sacred plant and the crown of his victors. He loved the youth Hyacinthus, killed by accident with a discus, from whose blood the hyacinth flower sprang. His arrows could heal - and could send plague upon armies, as he did to the Greeks at Troy.",
        'sources' => "Homeric Hymn to Apollo (3)\nHomer, Iliad 1.43-52 (the plague); 22.359 (slaying of Achilles)\nHesiod, Theogony 918-920\nApollodorus, Bibliotheca 1.4.1\nOvid, Metamorphoses 1.452-567 (Daphne); 10.162-219 (Hyacinthus)\nPausanias, Description of Greece 10.5-10.32 (Delphi)",
    ],
    'artemis' => [
        'bio' => "Artemis, twin sister of Apollo and daughter of Zeus and Leto, is the goddess of the hunt, the wild places, the moon, and the protection of young women in the transitions of girlhood and childbirth. Born on Delos a day before her brother - and by some accounts assisting in his delivery - she asked Zeus for a bow, a quiver, a band of nymphs, and eternal virginity. He granted everything she asked.\n\nHer life is bound up with the wilderness. She roams the mountains with her companions, hunting deer, boar, and bears with her silver bow. Her sanctity is fierce: when the hunter Actaeon stumbled upon her bathing, she transformed him into a stag and his own hounds tore him apart. When Niobe boasted that her many children made her superior to Leto, Artemis and Apollo killed Niobe's daughters with their arrows. When the maiden Callisto, one of her band, was seduced by Zeus, Artemis cast her out of her company.\n\nShe is also a protector. Pregnant women appealed to her for safe delivery, and young girls served her as 'little bears' in the rite of the arkteia at Brauron before marriage. Her great temple at Ephesus, with its many-breasted cult statue, was one of the Seven Wonders of the ancient world. Her sacred animals are the deer, the bear, and the dog, and her emblem is the silver crescent moon.",
        'sources' => "Callimachus, Hymn to Artemis (3)\nHomeric Hymn to Artemis (9, 27)\nHesiod, Theogony 918-920\nApollodorus, Bibliotheca 1.4.1; 3.4.4 (Actaeon)\nOvid, Metamorphoses 3.138-252 (Actaeon); 6.146-312 (Niobe)\nPausanias, Description of Greece 1.33 (Brauron); 7.5 (Ephesus)",
    ],
    'ares' => [
        'bio' => "Ares, son of Zeus and Hera, is the god of violent war - of bloodshed, slaughter, and the manic joy of battle. Where Athena represents the disciplined, strategic side of warfare, Ares embodies its uncontrolled fury. The Greeks themselves disliked him: in Homer's Iliad, his own father Zeus calls him 'the most hateful of the gods' for his love of strife and rejoicing in carnage. He fights for whichever side suits him and is often shown to be cowardly when faced with a stronger opponent.\n\nHis companions in battle are the war goddesses Enyo and Eris (Strife), and his sons Phobos and Deimos - Fear and Terror - drive his chariot. He had a long-standing affair with Aphrodite, the wife of Hephaestus, who caught them together in an unbreakable golden net of his own forging and exposed them to the laughter of the gods. From this union came Eros, Anteros, Phobos, Deimos, Harmonia, and others.\n\nAres is wounded twice in the Iliad - once by the mortal Diomedes with Athena's help, and again in single combat with Athena herself. He was bound for thirteen months in a bronze jar by the giants Otus and Ephialtes until Hermes rescued him. Despite his disrepute among the Olympians, Ares received cult in Thrace, his ancestral homeland, and at Sparta, the most martial city of Greece. The Romans, identifying him with Mars, would treat him with far greater honour.",
        'sources' => "Homer, Iliad 5.355-453; 5.835-909; 21.391-433\nHomer, Odyssey 8.266-366 (the net of Hephaestus)\nHesiod, Theogony 921-923, 933-937\nApollodorus, Bibliotheca 1.3.1; 3.4.1\nPausanias, Description of Greece 3.19 (Sparta)",
    ],
    'aphrodite' => [
        'bio' => "Aphrodite is the goddess of love, beauty, desire, and sexual pleasure - the irresistible force that draws bodies and hearts together. Greek myth offers two accounts of her birth. Hesiod tells that when Cronus castrated Uranus and threw the severed parts into the sea, the foam (aphros) that gathered around them gave birth to Aphrodite, who came ashore on Cyprus, and the island was sacred to her ever after. Homer, by contrast, calls her the daughter of Zeus and Dione.\n\nForced into marriage with Hephaestus, the lame smith god, she nonetheless took Ares as her lover, and her great love affair with the mortal Anchises produced the Trojan hero Aeneas. She also loved the youth Adonis, killed by a wild boar, whose annual death and return became the focus of women's festivals across the Mediterranean. Her son Eros (Cupid in Latin), armed with arrows of love, served as her constant companion.\n\nIt was Aphrodite who began the chain of events leading to the Trojan War. When the goddess Eris threw the golden apple inscribed 'for the fairest' among the goddesses, Paris of Troy was chosen to judge between Hera, Athena, and Aphrodite. Aphrodite promised him the most beautiful woman in the world - Helen of Sparta - and Paris's abduction of Helen ignited the war. Her sacred birds are the dove and the sparrow; her plants the rose, the myrtle, and the pomegranate; her emblem the magic girdle whose wearer becomes irresistible.",
        'sources' => "Hesiod, Theogony 188-206 (birth from sea foam)\nHomer, Iliad 5.311-431; Odyssey 8.266-366\nHomeric Hymn to Aphrodite (5) (Anchises)\nApollodorus, Bibliotheca 1.4.5; 3.14.4 (Adonis); 3.12.2 (judgment of Paris)\nOvid, Metamorphoses 10.503-739 (Adonis)",
    ],
    'hephaestus' => [
        'bio' => "Hephaestus is the god of fire, of the forge, of metallurgy and craftsmanship. He is the only Olympian with a physical disability: lame in both legs, either from birth or from his fall from heaven. The two accounts disagree. Hesiod tells that Hera bore him alone in jealousy of Zeus's birth of Athena; ashamed of his weakness, she cast him from Olympus, and he fell into the sea where the goddess Thetis raised him. Homer describes a different fall, when Hephaestus took his mother's part against Zeus and was hurled by Zeus from the heavens, falling for a whole day before landing on Lemnos.\n\nDespite his lameness, Hephaestus is the supreme artisan of the cosmos. He built the palaces of the gods on Olympus, forged Zeus's thunderbolts, the aegis, the chariot of Helios, the bronze giant Talos, the first woman Pandora, and the divine armour of Achilles described in book 18 of the Iliad - perhaps the most famous description of a work of art in ancient literature. He had divine assistants, mechanical women of gold who could speak and reason.\n\nHe was given Aphrodite as his bride, but she preferred Ares, and Hephaestus caught the lovers in a net of his own forging. His sanctuaries at Athens (where the Hephaisteion still stands beside the agora) and on the volcanic island of Lemnos honoured him as the god of fire and skilled craft. The Romans identified him with Vulcan, whose forges they placed beneath the volcanoes of Italy.",
        'sources' => "Homer, Iliad 1.571-600; 18.368-617 (the shield of Achilles); Odyssey 8.266-366\nHesiod, Theogony 927-929 (parthenogenetic birth)\nApollodorus, Bibliotheca 1.3.5\nPausanias, Description of Greece 1.14 (Hephaisteion)",
    ],
    'hermes' => [
        'bio' => "Hermes, son of Zeus and the nymph Maia, is the messenger of the gods and the most versatile of the Olympians. He is the patron of travellers, merchants, thieves, athletes, herdsmen, orators, and interpreters; the conductor of souls (psychopompos) to the underworld; the guardian of boundaries and roads, marked by the herm - a stone pillar with his head and male genitals. His name comes from herma, the heap of stones used to mark a path.\n\nThe Homeric Hymn to Hermes describes his precocious infancy. On the day of his birth he climbed out of his cradle, stole the cattle of his elder brother Apollo, drove them backwards to confuse the trail, and invented the lyre from a tortoise shell along the way. When Apollo discovered the theft, the infant charmed him with the new instrument, and Apollo accepted the lyre as compensation.\n\nHermes carries the kerykeion (caduceus), a herald's staff entwined with two serpents, and wears the winged sandals (talaria) and traveller's cap (petasos). He guided Priam through the Greek camp to ransom Hector's body, led the slain suitors of Penelope down to Hades, gave Odysseus the herb moly to resist Circe's spells, and helped Perseus to slay Medusa. Cunning, eloquent, and good-humoured, he is the closest of the gods to humanity and the most welcoming to those who travel.",
        'sources' => "Homeric Hymn to Hermes (4)\nHomer, Iliad 24.339-694; Odyssey 5.43-148; 10.275-308; 24.1-14\nHesiod, Theogony 938-939\nApollodorus, Bibliotheca 3.10.2\nPausanias, Description of Greece 8.17 (Cyllene, his birthplace)",
    ],
    'hestia' => [
        'bio' => "Hestia, eldest daughter of Cronus and Rhea, is the goddess of the hearth, of the household fire, and of the order of the family and the polis. The first to be swallowed by her father and the last to be disgorged, she is at once the eldest and youngest of the original Olympians. Both Apollo and Poseidon courted her, but she swore by the head of Zeus to remain a virgin forever, and Zeus granted her the central place in every home and the first share of every sacrifice.\n\nShe rarely appears as a character in narrative myth, but her presence is constant. The hearth fire was her - every meal began and ended with a libation to her, every new colony in the Greek world carried fire from the mother city's prytaneion (public hearth) to kindle her flame in their new home. The bride was led from her father's hearth to her husband's, and the newborn child was carried around the hearth in the amphidromia ritual. Her name means simply 'hearth'.\n\nIn the assembly of the Olympians she is sometimes counted as one of the twelve and sometimes replaced by Dionysus; the tradition that she yielded her seat to him reflects her quiet, retiring character. The Romans identified her with Vesta, whose Vestal Virgins kept the eternal flame of Rome on the Forum.",
        'sources' => "Hesiod, Theogony 453-457\nHomeric Hymn to Aphrodite (5) 21-32\nHomeric Hymn to Hestia (24, 29)\nApollodorus, Bibliotheca 1.1.5\nPausanias, Description of Greece 5.14, 8.9 (the prytaneia)",
    ],
    'dionysus' => [
        'bio' => "Dionysus is the god of wine, of vegetation and the cycle of fruitfulness, of ritual madness, theatre, and the loosening of ordinary bonds. Son of Zeus and the mortal princess Semele of Thebes, he is the only Olympian with a mortal mother. Hera, learning of Semele's pregnancy, persuaded the girl to demand that Zeus appear to her in his full divinity; the lightning of his presence consumed her, but Zeus rescued the unborn Dionysus and sewed him into his own thigh until he was ready to be born - hence the title 'twice-born'.\n\nRaised in secret by nymphs on Mount Nysa, Dionysus wandered the world teaching the cultivation of the vine and the rites of his worship. He travelled as far as India and back, accompanied by satyrs, the wine-old Silenus, and his ecstatic female followers, the maenads. Cities and kings who refused him were punished severely: Pentheus of Thebes, who tried to suppress his rites, was torn apart by his own mother in a bacchic frenzy, the central event of Euripides's Bacchae.\n\nHe descended to the underworld to bring his mother Semele back as the goddess Thyone, took the abandoned Ariadne as his bride after Theseus left her on Naxos, and presided over the Greek theatre - both tragedy and comedy were performed at his festivals in Athens, the Lenaia and the Great Dionysia. His emblems are the thyrsus (a fennel staff topped with a pinecone), the ivy crown, the panther, and the bull. The Romans called him Bacchus.",
        'sources' => "Euripides, Bacchae (full play)\nHomeric Hymn to Dionysus (1, 7, 26)\nHesiod, Theogony 940-942\nApollodorus, Bibliotheca 3.4.3-3.5.3\nOvid, Metamorphoses 3.259-733 (the Theban myths)\nPausanias, Description of Greece 1.20, 1.29 (theatre of Dionysus, Athens)",
    ],
    'persephone' => [
        'bio' => "Persephone, daughter of Demeter and Zeus, is the maiden of spring and queen of the underworld - a goddess of two realms and two names. As Kore ('the Maiden') she is the bringer of flowers and the youthful image of growth; as Persephone she is the dread queen who shares Hades's throne over the dead. The two identities reflect the great myth of her abduction.\n\nWhile gathering flowers in the Nysian meadow with her companions, the earth opened and Hades rose with his black chariot to carry her below. Demeter searched the world for her and, in her grief, brought famine to the earth. When the gods discovered Hades's hiding place, Zeus ordered her release - but Hades had given her seeds of pomegranate to eat, and one who has tasted the food of the dead cannot fully return. The compromise was that Persephone would spend a third of the year in the underworld with Hades and two-thirds above with her mother. The seasons follow her descent and return.\n\nIn the underworld she is no passive bride. She receives the heroes who come below - Heracles seeking Cerberus, Orpheus seeking Eurydice, Theseus and Pirithous seeking her own hand - and her judgement is heard alongside her husband's. The Eleusinian Mysteries, the most sacred initiation rite of ancient Greece, were founded on her story and promised initiates a place of joy in her domain after death.",
        'sources' => "Homeric Hymn to Demeter (full text)\nHesiod, Theogony 912-914\nApollodorus, Bibliotheca 1.5.1, 1.5.3\nOvid, Metamorphoses 5.385-571; Fasti 4.417-620\nPausanias, Description of Greece 1.38 (Eleusis); 8.37 (Phigalia)",
    ],

    // ======================== TITANS ========================
    'cronus' => [
        'bio' => "Cronus, youngest of the original twelve Titans, was the son of Uranus (Sky) and Gaia (Earth). When Uranus imprisoned his children - the Hundred-Handers and the Cyclopes - within the earth, Gaia in her pain forged a great adamantine sickle and called on her children to take revenge. Only Cronus dared. Lying in ambush at Gaia's instruction, he castrated his father with the sickle as Uranus came to lie with her, and the severed parts fell into the sea. From the blood that spattered the earth came the Furies, the Giants, and the Meliae nymphs; from the foam in the sea came Aphrodite.\n\nCronus took his sister Rhea as his wife and ruled in what later poets called the Golden Age - a time before toil, when the earth gave food freely and humankind lived without sorrow. But Uranus and Gaia had prophesied that Cronus, like his father before him, would be overthrown by his own son, and so he swallowed each of his children at birth: Hestia, Demeter, Hera, Hades, Poseidon. Rhea, in agony, hid the sixth child Zeus in Crete and gave Cronus a swaddled stone instead, which he swallowed unaware.\n\nGrown to manhood in secret, Zeus tricked Cronus into vomiting up the stone and his five elder siblings, then led them in the ten-year Titanomachy. Defeated, Cronus and most of the Titans were cast into Tartarus, though some traditions say he later ruled the Isles of the Blessed where heroes go after death. The Romans identified him with Saturn.",
        'sources' => "Hesiod, Theogony 132-210, 453-506, 617-735\nHesiod, Works and Days 109-126 (Golden Age)\nApollodorus, Bibliotheca 1.1.3-1.2.1\nPindar, Olympian 2.70-77 (Isles of the Blessed)\nPausanias, Description of Greece 5.7",
    ],
    'rhea' => [
        'bio' => "Rhea, daughter of Uranus and Gaia, is the great Titaness mother of the first Olympians: Hestia, Demeter, Hera, Hades, Poseidon, and Zeus. She married her brother Cronus and bore him these six children - but watched, year after year, as he swallowed each newborn whole to forestall the prophecy that his own offspring would overthrow him.\n\nWhen she conceived Zeus, Rhea could bear no more. On the advice of her parents Uranus and Gaia she fled to Crete and gave birth in secret in the Dictaean Cave. She gave Cronus a stone wrapped in swaddling cloth, which he swallowed believing it the infant. Zeus was raised by the Curetes, who clashed their bronze shields to drown out his cries, and by the goat Amalthea (or, in some tellings, the nymphs Adrasteia and Ida).\n\nRhea is the Earth Mother in another form - the great protective mother who safeguards her child against tyranny. Her cult merged readily with that of the Anatolian goddess Cybele, the Mountain Mother, whose ecstatic rites with cymbals and drums filled the Phrygian highlands. The Romans called her Magna Mater. Her sacred animal is the lion, often shown drawing her chariot, and her crown is sometimes turreted in the manner of Cybele.",
        'sources' => "Hesiod, Theogony 453-491\nApollodorus, Bibliotheca 1.1.3-1.1.5\nDiodorus Siculus 5.65, 5.70\nPausanias, Description of Greece 8.36 (Methydrium); 9.41 (rhea sanctuaries)",
    ],
    'atlas' => [
        'bio' => "Atlas, son of the Titan Iapetus and the Oceanid Clymene, was a leader of the Titans in the Titanomachy against Zeus. When the Titans were defeated, Zeus condemned Atlas to a particular punishment for his prominence: he was made to stand at the western edge of the world and hold the sky upon his shoulders forever, separating Heaven from Earth. The high mountains of northwestern Africa take his name from him, and ancient geographers placed him at the western boundary of the known world.\n\nHis name means 'Endurer' or 'Bearer'. He is the father of the Pleiades, the Hyades, and the nymph Calypso, and the brother of Prometheus and Epimetheus. He had little tolerance for visitors. When the hero Perseus passed through his realm and Atlas refused him hospitality, Perseus showed him the head of Medusa and turned him into the great mountain that bears his name - a variant tradition that gave the petrified Atlas a different end from the eternal sky-bearer.\n\nIn the labours of Heracles, Atlas appears again. Heracles, sent to fetch the golden apples of the Hesperides, asked Atlas - whose daughters guarded them - to retrieve the apples while Heracles himself bore the sky. Atlas brought the apples and tried to leave Heracles holding the sky permanently, but Heracles tricked him into taking it back, asking only to adjust the cushion on his shoulders.",
        'sources' => "Hesiod, Theogony 507-520\nHomer, Odyssey 1.52-54\nApollodorus, Bibliotheca 1.2.3; 2.5.11\nOvid, Metamorphoses 4.626-662\nPindar, Pythian 4.290; Isthmian 1.66",
    ],
    'prometheus' => [
        'bio' => "Prometheus, son of the Titan Iapetus, is the great culture-hero of Greek myth - the friend of humanity, the trickster who stole fire from heaven and gave it to mortals. His name means 'Forethought', and he is paired with his foolish brother Epimetheus ('Afterthought'), who was tasked with distributing gifts to the animals and used them all up before reaching humankind, leaving them naked and defenceless.\n\nIn Hesiod's account Prometheus first cheated Zeus at Mecone, dividing a sacrificed ox into two portions: one of meat hidden inside the unappetizing stomach, the other of bare bones disguised under glistening fat. Zeus chose the bones, and from then on mortals kept the meat and burned only the bones in sacrifice. Furious, Zeus withheld fire from humankind. Prometheus stole it back in a hollow fennel stalk and brought it to mortals - a gift of civilization itself, of cooking, metallurgy, and every art that depends on flame.\n\nFor this Zeus crucified him to a crag in the Caucasus, where each day an eagle came to feed on his liver, which grew back every night. He suffered for generations until Heracles, passing through on his way to fetch the golden apples, shot the eagle and broke his chains. Aeschylus's Prometheus Bound is the great tragedy of this myth, presenting Prometheus as the suffering champion of humanity against divine tyranny.",
        'sources' => "Hesiod, Theogony 507-616; Works and Days 42-105 (Pandora)\nAeschylus, Prometheus Bound (full play)\nApollodorus, Bibliotheca 1.7.1-1.7.2\nPlato, Protagoras 320c-322a (the gift of arts)",
    ],
    'themis' => [
        'bio' => "Themis is the Titaness of divine law, of order, of sacred custom, and of right by oath and prophecy. She is the daughter of Uranus and Gaia, and one of the few Titans to retain her honour fully into the Olympian order: she is consort of Zeus before Hera, and bore him the Horae (the Seasons) - Eunomia (Good Order), Dike (Justice), and Eirene (Peace) - and the Moirai, the three Fates who measure the thread of mortal life.\n\nHer name means 'that which is set down' - divine law, as distinct from the human conventions called nomos. She presides over the proper conduct of assemblies, the rights of suppliants and guests, the binding force of oaths, and the customs that hold the social order together. In Hesiod she is also the source of prophecy: she held the oracle at Delphi before Apollo, having received it from her mother Gaia, and only later passed it to him.\n\nIn art she appears as a stately woman holding scales - an emblem the Romans transferred to their goddess Iustitia, and which has become the modern symbol of justice itself. She advises Zeus in his great judgments, and in the Iliad it is Themis who summons the gods to assembly in his name. Her temple at Rhamnous in Attica preserved her cult into the classical period.",
        'sources' => "Hesiod, Theogony 132, 901-906\nHomer, Iliad 15.87-95; 20.4-6\nAeschylus, Eumenides 1-8 (Themis as predecessor at Delphi)\nApollodorus, Bibliotheca 1.3.1\nPausanias, Description of Greece 1.33 (Rhamnous); 10.5 (Delphi)",
    ],

    // ======================== HEROES ========================
    'heracles' => [
        'bio' => "Heracles (Roman Hercules), son of Zeus and the mortal princess Alcmene of Thebes, is the greatest hero of Greek myth - a figure of overwhelming physical strength, profound endurance, and tragic inner darkness. Hera, jealous of Alcmene, persecuted him from infancy, sending two serpents into his cradle, which the infant Heracles strangled with his bare hands.\n\nIn early manhood Hera struck him with madness, and in his frenzy he killed his wife Megara and their children. The oracle at Delphi commanded him to serve King Eurystheus of Tiryns for twelve years as penance, and from this servitude came the famous Twelve Labours: the Nemean Lion, the Lernaean Hydra, the Ceryneian Hind, the Erymanthian Boar, the Augean Stables, the Stymphalian Birds, the Cretan Bull, the Mares of Diomedes, the girdle of Hippolyta, the cattle of Geryon, the apples of the Hesperides, and Cerberus, the hound of Hades. He brought back every prize - sometimes by strength, sometimes by craft, sometimes by long suffering.\n\nBeyond the labours he performed countless additional feats - sacking Troy a generation before Agamemnon, fighting beside the gods against the Giants, freeing Prometheus from his eagle. He died through the inadvertent treachery of his second wife Deianeira, who anointed his shirt with what she believed was a love charm but was in fact the poisoned blood of the centaur Nessus. In agony he built his own pyre on Mount Oeta, and as the flames consumed his mortal part Zeus took him to Olympus, where he was reconciled with Hera and given the goddess Hebe as his wife.",
        'sources' => "Apollodorus, Bibliotheca 2.4.5-2.7.7 (the fullest narrative)\nHesiod, Theogony 287-294, 526-532\nHomer, Iliad 5.392-404; Odyssey 11.601-626\nEuripides, Heracles; Sophocles, Trachiniae (death of Heracles)\nDiodorus Siculus 4.8-4.39\nPindar, Olympian 3, Nemean 1, Isthmian 6",
    ],
    'perseus' => [
        'bio' => "Perseus, son of Zeus and the mortal princess Danaë of Argos, is one of the great heroes of pre-Trojan myth and the slayer of the Gorgon Medusa. His grandfather Acrisius, warned by an oracle that Danaë's son would kill him, locked her in a bronze chamber, but Zeus reached her as a shower of gold. When the child was born, Acrisius sealed mother and son in a chest and cast it into the sea; they drifted to the island of Seriphos, where the kindly fisherman Dictys took them in.\n\nThe king of Seriphos, Polydectes, desired Danaë and sent Perseus on what he believed an impossible errand: to bring back the head of Medusa, whose gaze turned the living to stone. Athena and Hermes guided him. From the Graeae - three grey witches with one eye and one tooth between them - he learned the way to the Nymphs of the North, who gave him winged sandals, the cap of Hades to make him invisible, and a bag to hold the head. With Athena's polished shield serving as a mirror so he need not look directly at the Gorgon, he beheaded Medusa in her sleep. From her blood sprang the winged horse Pegasus and the warrior Chrysaor.\n\nReturning home, he saved the princess Andromeda from a sea monster and married her, then turned the wicked Polydectes to stone with the Gorgon's head. He gave Medusa's head to Athena, who set it on her aegis. Perseus founded the city of Mycenae and was the ancestor of Heracles. The constellations Perseus, Andromeda, Cassiopeia, and Cepheus preserve his story.",
        'sources' => "Apollodorus, Bibliotheca 2.4.1-2.4.5\nHesiod, Theogony 270-282; Shield of Heracles 216-237\nOvid, Metamorphoses 4.610-803; 5.1-249\nPindar, Pythian 10.30-48; 12\nPausanias, Description of Greece 2.16-2.18 (Mycenae)",
    ],
    'achilles' => [
        'bio' => "Achilles, son of King Peleus of Phthia and the sea-goddess Thetis, is the greatest of the Achaean warriors at Troy and the central figure of Homer's Iliad. At his birth Thetis dipped him in the river Styx to render him invulnerable, holding him by the heel - the one place untouched by the water and his only weakness. (The 'Achilles heel' tradition is post-Homeric, first attested in Statius.) She also tried to make him immortal by burning away his mortal parts, but Peleus interrupted her, and she withdrew in grief.\n\nKnowing he would die at Troy, Thetis hid Achilles among the daughters of King Lycomedes on Scyros, dressed as a girl, but Odysseus discovered him with a trick - laying out gifts of jewellery and weapons before the maidens; when an alarm sounded, only Achilles seized a sword. He sailed to Troy with his Myrmidons and his beloved companion Patroclus, and for nine years he was the terror of the Trojan armies.\n\nThe Iliad opens in the tenth year, with Achilles's quarrel with Agamemnon over the captive woman Briseis. He withdrew from battle, allowing the Trojans to drive the Greeks back to their ships. Patroclus took his armour into the field and was killed by Hector. Achilles returned to battle in new armour forged by Hephaestus, slew Hector in single combat, and dragged the body around the walls of Troy. He died soon after, struck in the heel by an arrow from Paris guided by Apollo. After death his soul went to the Isles of the Blessed, where some traditions say he married Helen.",
        'sources' => "Homer, Iliad (the central hero); Odyssey 11.467-540 (afterlife)\nApollodorus, Epitome 3.13-5.5\nStatius, Achilleid (childhood and discovery on Scyros)\nPindar, Olympian 2.79; Nemean 3, 4\nPausanias, Description of Greece 3.19 (cult on Leuke)",
    ],
    'odysseus' => [
        'bio' => "Odysseus (Roman Ulysses), king of Ithaca, son of Laertes (or in some traditions Sisyphus) and Anticlea, is the great wanderer of Greek myth and the hero of Homer's Odyssey. Famed not for strength but for cunning intelligence (mētis), eloquence, and endurance, he is the favoured mortal of the goddess Athena.\n\nReluctant to leave his wife Penelope and infant son Telemachus, he feigned madness when summoned to Troy, ploughing his fields with salt - until Palamedes placed Telemachus in the path of the plough and Odysseus turned aside, revealing his sanity. At Troy he served as the chief counsellor of the Greek kings. He fought, embassied, spied within the city walls, and finally devised the ruse of the Wooden Horse that brought the city down.\n\nHis homeward journey took ten years, the subject of the Odyssey. He blinded the Cyclops Polyphemus (Poseidon's son, earning the sea god's lasting hatred), survived the witch Circe (who turned his men into swine until Hermes gave him the herb moly), descended into Hades to consult the prophet Tiresias, sailed past the Sirens bound to the mast, and lost all his companions in the strait of Scylla and Charybdis and the cattle of the Sun. He spent seven years held by the nymph Calypso on Ogygia. Returning at last to Ithaca disguised as a beggar, he killed the suitors who had occupied his palace and harassed Penelope, was reunited with his wife by the secret of their marriage bed, and reclaimed his kingdom.",
        'sources' => "Homer, Odyssey (the central poem); Iliad 2, 9-10, 14, 19, 23\nApollodorus, Epitome 3.6-7.40\nSophocles, Ajax, Philoctetes\nEuripides, Hecuba, Trojan Women, Cyclops\nVirgil, Aeneid 2 (the Wooden Horse)\nOvid, Metamorphoses 13-14",
    ],
    'atalanta' => [
        'bio' => "Atalanta is the great huntress and runner of Greek myth - the mortal woman who matched and surpassed the heroes of her age in the chase, the foot-race, and the bow. Born in Arcadia (or Boeotia, in another tradition) to a king who had wanted a son, she was exposed in the wilderness as an infant; a she-bear suckled her, and a band of hunters raised her. She grew up wild, devoted to Artemis, and sworn to virginity.\n\nShe joined the heroes who hunted the Calydonian Boar - a monstrous beast sent by Artemis to ravage the kingdom of Calydon - and drew first blood with her arrow. The hero Meleager, who delivered the killing blow, awarded her the hide as the day's chief honour, sparking a quarrel that led to his own destruction. She also competed in the funeral games of Pelias, where she defeated Peleus in wrestling.\n\nWhen her royal father reclaimed her and pressed her to marry, Atalanta agreed only on the condition that any suitor must beat her in a foot-race; if he lost, he died. Many died. Then a youth named Hippomenes (or Melanion in some sources) prayed to Aphrodite, who gave him three golden apples from the garden of the Hesperides. As he ran he dropped them in turn; Atalanta paused to pick each one up, and Hippomenes won the race and her hand. Their later love-making in a sacred precinct angered the gods, who transformed them into a pair of lions.",
        'sources' => "Apollodorus, Bibliotheca 3.9.2; Library Epitome 1.7-1.9\nOvid, Metamorphoses 8.260-546 (Calydonian Boar); 10.560-680 (the race)\nHesiod, Catalogue of Women fr. 73-76 M-W\nPausanias, Description of Greece 3.24, 8.45\nHyginus, Fabulae 70, 99, 173-174, 185",
    ],

    // ======================== MONSTERS ========================
    'medusa' => [
        'bio' => "Medusa, the only mortal of the three Gorgons, is among the most famous monsters of Greek myth. Her sisters Stheno and Euryale were immortal; Medusa alone could be slain. Hesiod calls them daughters of the primordial sea deities Phorcys and Ceto and places them in the far west of the world, beyond the stream of Ocean, where the night and the singing Hesperides dwell.\n\nA later tradition, told most fully by Ovid, makes her a beautiful priestess of Athena who was raped by Poseidon in the goddess's temple. Athena, unable to punish Poseidon, turned Medusa's beauty into terror: her hair became a tangle of living serpents, her gaze turned the living to stone, and she was banished to the edge of the world. Her face - bristling, fanged, with a stuck-out tongue - became one of the most common protective images in Greek art, set on shields, doorways, and tomb markers to ward off evil.\n\nThe hero Perseus was sent by King Polydectes to fetch her head. Guided by Athena and Hermes, equipped with the cap of darkness, winged sandals, an adamantine sickle, and a bag, he found her sleeping with her sisters and beheaded her using Athena's polished shield as a mirror so as not to meet her eye. From her severed neck sprang the winged horse Pegasus and the warrior Chrysaor. Perseus carried the head as a weapon and finally gave it to Athena, who fixed it upon her aegis where it remained forever.",
        'sources' => "Hesiod, Theogony 270-283\nOvid, Metamorphoses 4.610-803 (origin myth)\nApollodorus, Bibliotheca 2.4.2-2.4.3\nPindar, Pythian 12\nPausanias, Description of Greece 2.21",
    ],
    'minotaur' => [
        'bio' => "The Minotaur - Asterion in some tellings - was the bull-headed son of Pasiphaë, queen of Crete, and the magnificent white bull sent from the sea by Poseidon. King Minos had promised to sacrifice the bull to Poseidon but, struck by its beauty, kept it for himself. In retribution Poseidon caused Pasiphaë to fall in love with the animal. The craftsman Daedalus built her a hollow wooden cow in which she could mate with the bull, and the offspring of that union was the Minotaur, a being with the body of a man and the head of a bull, bellowing and ravenous for human flesh.\n\nMinos commanded Daedalus to construct a vast underground maze, the Labyrinth, to contain the creature. After his son Androgeos was killed at Athens, Minos exacted from the Athenians a tribute of seven young men and seven young women every nine years (or every year, in other versions), to be sent into the Labyrinth as food for the Minotaur.\n\nThe Athenian prince Theseus volunteered for the third tribute, intending to kill the beast. In Crete he met Minos's daughter Ariadne, who fell in love with him and gave him a ball of thread (the clew) so that he could find his way back out of the maze. He killed the Minotaur in single combat at its heart, retraced his thread, and sailed away with Ariadne.",
        'sources' => "Apollodorus, Bibliotheca 3.1.4; 3.15.8; Epitome 1.7-1.11\nDiodorus Siculus 4.61\nPlutarch, Theseus 15-19\nOvid, Metamorphoses 8.131-176\nPausanias, Description of Greece 1.17, 1.27",
    ],
    'cerberus' => [
        'bio' => "Cerberus is the great hound of Hades - the three-headed dog (in some accounts fifty-headed or even hundred-headed) who guards the gates of the underworld, allowing the souls of the dead to pass in but never to leave. Offspring of Typhon and Echidna, the parents of nearly every monster in Greek myth, he is brother to the Lernaean Hydra, the Chimera, and Orthus, the two-headed dog of Geryon.\n\nA serpent often takes the place of his tail, and snakes coil from his back. His drool, dropping onto the soil, is said to have given rise to the deadly herb aconite. Only the music of Orpheus could lull him to sleep - and even then only for the length of one song.\n\nThe twelfth and most dangerous of the labours of Heracles was the capture of Cerberus. Without weapons, by Eurystheus's command, the hero descended to the underworld, was admitted by Hades and Persephone on the condition that he take the dog by sheer strength, and wrestled him to submission. He carried him up into the daylight, showed him to the terrified Eurystheus, and then released him to return to his post. Heracles is the only mortal to have entered Hades and emerged with the hound.",
        'sources' => "Hesiod, Theogony 311-312, 769-774\nApollodorus, Bibliotheca 2.5.12\nVirgil, Aeneid 6.417-425\nOvid, Metamorphoses 4.450; 7.408-419 (origin of aconite)\nPausanias, Description of Greece 3.25 (cape Tainaron)",
    ],
    'hydra' => [
        'bio' => "The Lernaean Hydra was a many-headed water serpent that haunted the swamps and springs of Lerna, near Argos. Born of Typhon and Echidna and reared by Hera specifically to be a danger to Heracles, she dwelled at the source of the river Amymone, in a region the Greeks regarded as one of the entrances to the underworld. The number of her heads is given variously as nine, fifty, or a hundred, and one of them was immortal.\n\nThe second of Heracles's twelve labours was to slay her. The hero discovered at once that for every head he severed, two grew back from the stump. His nephew and charioteer Iolaus then took up a torch and seared each fresh wound as Heracles cut, preventing new heads from growing. Heracles buried the immortal head, still hissing, beneath a great stone by the road.\n\nFrom her venomous blood Heracles dipped his arrows, which thereafter inflicted incurable wounds - the same arrows that would later kill the centaur Nessus, fall accidentally on Chiron, and ultimately bring about Heracles's own death through the poisoned cloak of Deianeira. King Eurystheus refused to count this labour as fulfilled because Iolaus had helped, and added one more to the list. The constellation Hydra preserves her in the southern sky.",
        'sources' => "Hesiod, Theogony 313-318\nApollodorus, Bibliotheca 2.5.2\nDiodorus Siculus 4.11\nOvid, Metamorphoses 9.69-76, 158-204\nPausanias, Description of Greece 2.37 (Lerna)",
    ],
    'chimera' => [
        'bio' => "The Chimera was a fire-breathing hybrid monster that ravaged the kingdom of Lycia in southwestern Asia Minor. Homer describes her as a creature 'in front a lion, behind a serpent, and in the middle a goat' - three animal natures fused into one body. Hesiod adds that she had three heads, one of each beast, and breathed flame from all of them. She was the daughter of Typhon and Echidna, and the sister of Cerberus, the Hydra, and the Sphinx.\n\nKing Iobates of Lycia received the young hero Bellerophon, a guest sent by his son-in-law Proetus with a sealed letter requesting that the bearer be killed. Reluctant to break the laws of hospitality directly, Iobates sent Bellerophon against the Chimera, expecting his death. With the help of the goddess Athena, who gave him a golden bridle, Bellerophon caught and tamed the winged horse Pegasus, born from Medusa's blood. From the air, beyond reach of her flames, he attacked the Chimera, finally killing her by thrusting a lump of lead on the tip of his spear into her mouth, which the fire melted and ran down her throat.\n\nThe Greeks identified the myth with a region of Lycia where natural gas vents in the ground had burned continuously for millennia (the modern Yanartaş in Turkey), explaining the fire-breathing creature as a mythologization of the eternal flames. Her name has given English the word 'chimera' for any wild fancy or impossible composite.",
        'sources' => "Homer, Iliad 6.179-183\nHesiod, Theogony 319-325\nApollodorus, Bibliotheca 2.3.1-2.3.2\nPindar, Olympian 13.84-90; Isthmian 7.44\nOvid, Metamorphoses 9.647",
    ],
    'sphinx' => [
        'bio' => "The Sphinx of Thebes was a winged monster with the body of a lion, the breasts and face of a woman, and the tail (in some accounts) of a serpent. The Greeks distinguished her from the male, beardless sphinxes of Egypt: she was a destroyer who came from the south, sat above the city of Thebes, and devoured every traveller who could not answer her riddle. Hesiod calls her the daughter of the Chimera and Orthus, the two-headed dog; in other traditions she is the offspring of Typhon and Echidna.\n\nHer riddle, in its most famous version, is: 'What walks on four legs in the morning, two legs at noon, and three legs in the evening?' The whole Theban kingdom suffered under her plague, until the young exile Oedipus, fleeing the prophecy that he would kill his father and marry his mother, came to the city. He answered: 'A human being - who crawls in infancy, walks upright in maturity, and uses a staff in old age.' Defeated, the Sphinx hurled herself from her cliff and died.\n\nFor solving the riddle Oedipus was made king of Thebes and married the widowed queen Jocasta - who, unknown to either, was his mother. The myth of the Sphinx is the threshold of the great Theban tragedy, told most powerfully in Sophocles's Oedipus the King.",
        'sources' => "Hesiod, Theogony 326-329\nApollodorus, Bibliotheca 3.5.8\nSophocles, Oedipus Tyrannus 391-398, 1525\nPausanias, Description of Greece 9.26\nDiodorus Siculus 4.64",
    ],
    'typhon' => [
        'bio' => "Typhon - also called Typhoeus - is the most monstrous of all creatures in Greek myth, the last and greatest challenge to the rule of Zeus. Hesiod describes him as the youngest son of Gaia and Tartarus, born after the defeat of the Titans and the Giants in revenge against the Olympians. He was a being of overwhelming size: a hundred serpent-heads grew from his shoulders, his eyes flashed fire, his voices roared like lions and bellowed like bulls and hissed like snakes, and the upper air shook when he moved.\n\nHe assaulted Olympus to overthrow Zeus and seize the rule of the cosmos. The other gods, in terror, fled to Egypt and disguised themselves as animals - a story by which Greek writers explained the animal-headed gods of Egyptian religion. Only Zeus stood his ground. In a battle that shook the foundations of the world, Zeus struck him with thunderbolt after thunderbolt and finally hurled the burning monster down beneath Mount Etna, where his struggles still cause volcanic eruptions, and his hot breath rises through the chimney of the volcano.\n\nWith Echidna, his serpentine consort, Typhon fathered most of the great monsters of Greek legend: Cerberus, the Hydra, the Chimera, the Nemean Lion, the Sphinx, Orthus, and the eagle that ate the liver of Prometheus. His defeat marked the final consolidation of Zeus's rule and the end of the age of cosmic conflict.",
        'sources' => "Hesiod, Theogony 820-880\nApollodorus, Bibliotheca 1.6.3\nHomeric Hymn to Apollo 305-355\nPindar, Pythian 1.15-28; Olympian 4.6-7\nOvid, Metamorphoses 5.318-358 (gods flee to Egypt)",
    ],
];

// 3. Apply updates
$ok = 0;
$skipped = 0;
$failed = 0;

foreach ($updates as $slug => $data) {
    $stmt = $conn->prepare("UPDATE characters SET full_bio = ?, sources = ? WHERE slug = ?");
    if (!$stmt) {
        echo "[!] Prepare failed for $slug: " . $conn->error . "\n";
        $failed++;
        continue;
    }
    $stmt->bind_param('sss', $data['bio'], $data['sources'], $slug);
    if ($stmt->execute()) {
        if ($stmt->affected_rows > 0) {
            echo "[+] Updated $slug\n";
            $ok++;
        } else {
            // Either the row doesn't exist or content was identical
            $check = $conn->prepare("SELECT slug FROM characters WHERE slug = ?");
            $check->bind_param('s', $slug);
            $check->execute();
            $exists = $check->get_result()->num_rows > 0;
            $check->close();
            if ($exists) {
                echo "[=] $slug already up to date\n";
                $ok++;
            } else {
                echo "[?] No row found for $slug - run seed_characters.php first\n";
                $skipped++;
            }
        }
    } else {
        echo "[!] Update failed for $slug: " . $stmt->error . "\n";
        $failed++;
    }
    $stmt->close();
}

$conn->close();

echo "\n----------------------------------------\n";
echo "Done. " . count($updates) . " characters processed.\n";
echo "  Updated: $ok\n";
echo "  Skipped: $skipped\n";
echo "  Failed:  $failed\n";
echo "</pre>";
