<?php
// upgrade_myths.php by Eduardo Bussien
// Run ONCE in your browser: http://localhost/olympus/sql/upgrade_myths.php
// Adds a `sources` column (if missing) and rewrites every myth's full_text
// with an expanded retelling plus citations to ancient sources.
// Safe to run multiple times - uses UPDATE on existing rows.

require __DIR__ . '/db.php';

header('Content-Type: text/html; charset=utf-8');
echo "<pre style='font-family:monospace;font-size:13px;line-height:1.5;'>";

// 1. Add sources column if missing
$colCheck = $conn->query("SHOW COLUMNS FROM myths LIKE 'sources'");
if ($colCheck && $colCheck->num_rows === 0) {
    if ($conn->query("ALTER TABLE myths ADD COLUMN sources TEXT NULL AFTER full_text")) {
        echo "[+] Added column `sources` to `myths`\n";
    } else {
        echo "[!] Failed to add column: " . $conn->error . "\n";
        exit;
    }
} else {
    echo "[=] Column `sources` already exists\n";
}

// 2. Expanded retellings + sources for every myth
$updates = [
    'primordial-chaos' => [
        'text' => "In the beginning there was only Chaos - not disorder, but a yawning emptiness, a vast and shapeless gulf without form or limit. Hesiod, the earliest Greek poet to set down the cosmogony, says simply that 'first of all Chaos came to be.' From this primal void emerged the first powers of the cosmos, each born without parent and each setting in motion a different aspect of existence.\n\nFirst came Gaia, the broad-breasted Earth, the everlasting foundation of all the gods who would follow. Then Tartarus, the misty pit beneath the deepest roots of the earth, where the future enemies of the gods would be cast. And finally Eros, the loveliest among the immortals - not the playful boy of later poetry but a primordial force, the power of attraction by which all things would join, generate, and become.\n\nFrom Chaos itself were also born Erebus, the deep darkness, and Nyx, the black-winged Night. From the union of Erebus and Nyx came Aether, the bright upper air, and Hemera, the Day. The cosmos now had a frame: earth below, abyss beneath that, darkness and light above. The age of generation could begin, and Gaia, alone, would bring forth Uranus to be her equal.",
        'sources' => "Hesiod, Theogony 116-138\nApollodorus, Bibliotheca 1.1.1\nOvid, Metamorphoses 1.5-20\nAristophanes, Birds 693-702\nHyginus, Fabulae preface 1-2",
    ],
    'birth-of-the-titans' => [
        'text' => "Gaia, the Earth, brought forth Uranus the starry sky to cover her on every side, and from their union were born the first great race of immortals - the Titans. Hesiod names twelve: Oceanus the world-encircling river, Coeus, Crius, Hyperion, Iapetus, Theia, Rhea, Themis, Mnemosyne, Phoebe, Tethys, and the youngest and craftiest of them, Cronus. After the Titans came the three Cyclopes - Brontes, Steropes, and Arges - each with a single eye in the centre of his forehead, and after them the three Hundred-Handers - Cottus, Briareos, and Gyges - each with fifty heads and a hundred mighty arms.\n\nUranus loathed his children. As each was born he forced them back into the depths of Gaia's body, hating them for their power and their strangeness. Gaia groaned under the burden and her grief turned to rage. She brought forth a great adamantine sickle and called upon her children to free her - but only Cronus, the youngest, dared to take up the weapon.\n\nThat night, when Uranus came down to lie with Gaia, Cronus sprang from his hiding place and castrated his father with a single stroke. The severed parts fell into the sea; from the blood that splashed upon the earth sprang the Furies, the Giants, and the Meliae nymphs of the ash trees. From the foam that gathered around the parts in the sea came Aphrodite, drifting at last to shore on Cyprus. Uranus, ruined and powerless, retreated forever, and Cronus took his place as lord of the cosmos.",
        'sources' => "Hesiod, Theogony 132-210\nApollodorus, Bibliotheca 1.1.3-1.1.4\nDiodorus Siculus 5.66\nHyginus, Fabulae preface 3-5\nPausanias, Description of Greece 8.36",
    ],
    'titanomachy' => [
        'text' => "Cronus ruled in fear after overthrowing Uranus. The same prophecy that had doomed his father - that he would be cast down by his own son - clung to him too, and so he swallowed each child Rhea bore him: Hestia, Demeter, Hera, Hades, Poseidon. Rhea, in agony at the loss of her sixth child, fled to Crete and gave birth to Zeus in the secret of the Dictaean Cave. She gave Cronus a stone wrapped in swaddling cloth, which he swallowed believing it the infant.\n\nGrown to manhood in hiding, fed by the goat Amalthea and shielded by the noisy Curetes who clashed their bronze shields to drown his cries, Zeus returned to Olympus. With the cunning of his ally Metis he forced Cronus to vomit up the swallowed children, who emerged grown and ready for war. Zeus also descended into Tartarus and freed the Cyclopes and the Hundred-Handers, whom Cronus had imprisoned. In gratitude the Cyclopes forged for him the thunderbolt, for Poseidon the trident, and for Hades the helm of darkness.\n\nThus armed, the Olympians and the Titans fought for ten long years from their opposing fortresses - Olympus and Othrys - shaking the cosmos. The decisive moment came when the Hundred-Handers hurled three hundred boulders at once and Zeus loosed his thunderbolts together, rolling fire across earth, sea, and sky. The Titans fell. They were chained in Tartarus and the Hundred-Handers set as their guardians. Zeus and his brothers cast lots for the cosmos: the heavens went to Zeus, the sea to Poseidon, the underworld to Hades; the earth and Olympus they held in common. The age of the Olympians had begun.",
        'sources' => "Hesiod, Theogony 453-506, 617-735\nApollodorus, Bibliotheca 1.1.5-1.2.1\nHomer, Iliad 8.478-481; 14.279; 15.187-193\nDiodorus Siculus 5.70-71\nPausanias, Description of Greece 5.7",
    ],
    'birth-of-athena' => [
        'text' => "Zeus, newly enthroned, took the wise Titaness Metis as his first consort. But Gaia and Uranus warned him of a prophecy: any son Metis bore would surpass even Zeus and overthrow him as Zeus had overthrown his father. To forestall this fate, Zeus tricked Metis into making herself small and swallowed her whole - much as Cronus had once swallowed his own children. Metis, however, was already pregnant, and within Zeus's body she set about forging armour and a helmet for the unborn child.\n\nThe time came when the child was ready to be born. Zeus suffered a splitting headache so terrible that he begged the gods for relief. Hephaestus, the smith, took up his great axe and cleaved Zeus's skull. From the wound leapt Athena, fully grown, fully armed in her gleaming armour, brandishing a spear and uttering a war cry that shook heaven, earth, and sea.\n\nBecause she had no human conception or upbringing, no time of mortal weakness, Athena emerged perfect: the goddess of wisdom and strategic warfare, of weaving and craftsmanship, of cities and the institutions that hold them together. She would never marry, never love, but would become the great patroness of heroes - Perseus, Heracles, Bellerophon, Odysseus - and the chosen guardian of Athens. The myth of her birth, dramatic and unique among the Olympians, marked her as a goddess unlike any other.",
        'sources' => "Hesiod, Theogony 886-900, 924-926\nHomeric Hymn to Athena (28)\nPindar, Olympian 7.35-38\nApollodorus, Bibliotheca 1.3.6\nAeschylus, Eumenides 736-740",
    ],
    'creation-of-humans' => [
        'text' => "When the immortal gods had been established and the cosmos was set in order, the time came to populate the earth with mortal creatures. The task was given to two brothers among the Titans: Prometheus, whose name means 'forethought,' and Epimetheus, whose name means 'afterthought.' Epimetheus took on the duty of distributing gifts to each species - speed, strength, fur, claws, scales, wings - and through his impulsive generosity used up every gift before he reached humankind, leaving them naked, weaponless, and shivering.\n\nPrometheus, seeing what his brother had done, took clay from the riverbanks of Panopeus, mixed it with water, and shaped the first humans in the image of the gods. Athena breathed life into them. But they remained helpless: they did not know how to cook, how to forge, how to keep warm in winter. Zeus, jealous of the divine prerogative of fire, refused to share it with the new race.\n\nProtector of his creation, Prometheus stole fire from the workshop of Hephaestus on Olympus, hiding a glowing ember inside a hollow fennel stalk, and brought it down to mortals. With fire came every art that civilization depends on - cooking, metallurgy, pottery, sacrifice. With fire, humanity ceased to be merely the weakest of animals and became something like the gods themselves. Zeus's fury at this theft would set in motion the punishment of Prometheus and the creation of Pandora.",
        'sources' => "Hesiod, Theogony 507-616; Works and Days 42-105\nPlato, Protagoras 320c-322a (the gift of arts)\nAeschylus, Prometheus Bound 442-506\nApollodorus, Bibliotheca 1.7.1\nOvid, Metamorphoses 1.76-88",
    ],
    'punishment-of-prometheus' => [
        'text' => "Zeus's anger at Prometheus's theft of fire was not appeased by the creation of Pandora alone. He ordered the Titan seized and dragged to the harshest edge of the world - to the high crags of the Caucasus mountains, beyond the lands of mortals, where the cold winds never cease and no human eye could witness his suffering. There, by the hands of Cratus (Power) and Bia (Force), Prometheus was bound to the rock with chains forged by Hephaestus, who wept as he riveted them in place, for he too had been a friend of the prisoner.\n\nEvery day at dawn, an enormous eagle - in some accounts a son of Typhon and Echidna - flew to the cliff and tore open Prometheus's side with its iron beak, devouring his liver. Because Prometheus was immortal, the liver grew back each night, only to be torn out again the next morning. He hung there for thirty thousand years (in some accounts), enduring without end, refusing to bow to Zeus or beg release.\n\nIn Aeschylus's great tragedy, Prometheus speaks not as a victim but as the proud champion of humankind, foreseeing his own eventual liberation. That liberation came at last from the hero Heracles, who, passing the Caucasus on his way to fetch the apples of the Hesperides, drew his bow and shot the eagle dead. Zeus, mellowed by the passage of ages, allowed his old enemy to be set free - though Prometheus was made to wear an iron ring set with a fragment of the rock to which he had been chained, so that the letter of Zeus's vow that Prometheus would never be unbound could still be kept.",
        'sources' => "Hesiod, Theogony 521-525\nAeschylus, Prometheus Bound (full play)\nApollodorus, Bibliotheca 2.5.11\nHyginus, Astronomica 2.15\nPausanias, Description of Greece 5.11",
    ],
    'pandoras-box' => [
        'text' => "After Prometheus had stolen fire from the gods, Zeus determined to balance the gift with a curse. He commanded Hephaestus to mould out of clay a beautiful young woman, the first mortal female. The other gods adorned her: Athena dressed her and taught her weaving, Aphrodite gave her grace, the Hours and Graces hung gold ornaments upon her, Hermes placed in her breast a cunning mind and the voice to use it. Her name was Pandora - 'all-gifted' - because she received gifts from every god.\n\nZeus sent her to Epimetheus, the foolish brother, with a sealed jar (in the original Greek, a pithos - a great storage vessel; the 'box' is a later mistranslation by Erasmus). Prometheus had warned his brother to accept no gift from Zeus, but at the sight of Pandora Epimetheus forgot the warning and made her his wife. With her she had brought the jar.\n\nUnable to resist her curiosity - for which the gods had perhaps designed her - Pandora lifted the lid. Out poured every evil that afflicts humankind: hard labour, painful diseases, jealousy, old age, madness, death itself. They flew out in dark clouds and scattered across the world, where they remain to this day. Pandora slammed the lid shut just in time to keep one thing inside: Elpis, Hope. Whether Hope was a comfort imprisoned for humanity's good or another curse withheld is a question Hesiod does not answer, and the ambiguity has haunted readers for thousands of years.",
        'sources' => "Hesiod, Works and Days 47-105; Theogony 570-612\nApollodorus, Bibliotheca 1.7.2\nAesop, Fables 526 (Hope variation)\nHyginus, Fabulae 142\nBabrius 58 (the jar of evils)",
    ],
    'labors-of-heracles' => [
        'text' => "Driven mad by Hera's lifelong hatred, Heracles in his frenzy killed his own wife Megara and their children. When the madness lifted and he saw what he had done, he sought purification at the oracle of Delphi, which commanded him to serve King Eurystheus of Tiryns and perform whatever labours that king set him for ten (later twelve) years. Through these tasks his sin would be cleansed and his name made immortal.\n\nThe twelve labours were: to slay the Nemean Lion (whose hide no weapon could pierce); to slay the Lernaean Hydra (whose heads grew back when severed); to capture the Ceryneian Hind (sacred to Artemis); to capture the Erymanthian Boar; to clean the stables of Augeas in a single day (which he did by diverting two rivers); to drive away the Stymphalian Birds; to capture the Cretan Bull; to seize the man-eating Mares of Diomedes; to fetch the girdle of Hippolyta, queen of the Amazons; to drive home the cattle of the giant Geryon from the western edge of the world; to bring back the golden apples of the Hesperides (the labour for which Atlas held the sky); and finally, the most dangerous of all, to descend into Hades and bring up Cerberus.\n\nEurystheus refused to accept two of the labours - the Hydra (because Iolaus had helped) and the Augean stables (because they had been done for pay) - and so set additional tasks to make twelve in all. Heracles completed every one. The labours took him to every corner of the known world, made him the friend and ally of countless kings and gods, and earned him at last the place on Olympus that no other mortal would receive.",
        'sources' => "Apollodorus, Bibliotheca 2.5.1-2.5.12 (the canonical sequence)\nDiodorus Siculus 4.11-4.27\nEuripides, Heracles 359-435\nHesiod, Theogony 313-318, 327-332\nPausanias, Description of Greece 1.27, 2.31, 5.10",
    ],
    'perseus-and-medusa' => [
        'text' => "King Polydectes of Seriphos desired Danaë, the mother of the young Perseus, but the boy stood in his way. Pretending to require gifts for his wedding to another woman, the king demanded each guest bring a horse - knowing Perseus could not afford one. Stung into rashness, Perseus boasted that he would bring something better: the head of Medusa, the only mortal of the three Gorgons, whose gaze turned the living to stone. Polydectes seized on the boast and held him to it.\n\nThe gods had not abandoned him. Athena gave him a polished bronze shield, Hermes a curved adamantine sickle and his own winged sandals. From the Graeae - three grey witches who shared one eye and one tooth between them - Perseus learned the way to the Nymphs of the North, who gave him a kibisis (a magic bag) and the cap of Hades, which made its wearer invisible. Thus equipped, he flew to the cave at the western edge of the world where the Gorgons slept.\n\nUsing the shield as a mirror so as not to meet Medusa's eye directly, he beheaded her with a single stroke of the sickle. From her severed neck sprang the winged horse Pegasus and the golden warrior Chrysaor - children fathered on her by Poseidon. Stuffing the head into the kibisis, Perseus flew home, rescuing Andromeda from a sea monster on the way. He turned Polydectes and his court to stone with the trophy, then gave the head to Athena, who fixed it forever upon her aegis as the protective Gorgoneion.",
        'sources' => "Apollodorus, Bibliotheca 2.4.1-2.4.5\nHesiod, Theogony 270-283; Shield of Heracles 216-237\nOvid, Metamorphoses 4.610-803; 5.1-249\nPindar, Pythian 12\nPausanias, Description of Greece 2.16",
    ],
    'theseus-and-the-minotaur' => [
        'text' => "King Minos of Crete had once promised to sacrifice a magnificent white bull sent by Poseidon, but he kept the bull for himself in defiance of the god. In retribution Poseidon caused Minos's queen Pasiphaë to fall in love with the animal. The craftsman Daedalus built her a hollow wooden cow in which she could mate with the bull, and the offspring was the Minotaur - a being with the body of a man and the head of a bull, ravenous for human flesh. Minos commanded Daedalus to construct a vast underground maze, the Labyrinth, to contain the creature.\n\nAfter Minos's son Androgeos was killed at the games of Athens, Minos exacted from the Athenians a tribute of seven young men and seven young women every nine years (every year, in some versions), to be sent into the Labyrinth as food for the Minotaur. When the third tribute was due, the prince Theseus, son of King Aegeus, volunteered to be among the victims, intending to kill the beast.\n\nIn Crete, Minos's daughter Ariadne saw Theseus and fell in love with him. She gave him a ball of thread (the clew) so that he could find his way back through the maze, and a sword to slay the monster. He killed the Minotaur in single combat at its dark heart, retraced the thread to the entrance, freed the surviving Athenian youths, and sailed for home with Ariadne - whom he abandoned on the island of Naxos, where the god Dionysus would find and marry her. Theseus had promised his father that he would change his ship's black sails to white if he returned alive, but in his haste he forgot. Aegeus, watching from the cliff and seeing the black sails, threw himself into the sea, which has borne his name ever since.",
        'sources' => "Apollodorus, Epitome 1.7-1.11; Bibliotheca 3.1.4, 3.15.8\nPlutarch, Theseus 15-22\nDiodorus Siculus 4.61\nOvid, Metamorphoses 8.131-176\nCatullus 64.50-264 (Ariadne on Naxos)",
    ],
    'jason-and-the-golden-fleece' => [
        'text' => "Pelias had usurped the throne of Iolcus from Jason's father Aeson. When Jason came of age and demanded his rightful inheritance, Pelias agreed - on condition that Jason first travel to the distant kingdom of Colchis on the eastern shore of the Black Sea and bring back the Golden Fleece, the hide of a magical winged ram that hung in a sacred grove guarded by a sleepless dragon. Pelias expected the quest to kill him.\n\nJason gathered the greatest heroes of his generation and built the ship Argo, named for its builder Argus. Among the Argonauts were Heracles, the twins Castor and Polydeuces, the seer Mopsus, the singer Orpheus, the swift Atalanta, and many more. They sailed past the Symplegades - the clashing rocks at the entrance of the Black Sea, which Jason passed by sending a dove ahead and rowing through behind it. They survived the harpies who tormented the blind seer Phineus, the king of the Bebryces, and many other trials.\n\nIn Colchis, King Aeetes set Jason impossible tasks before he would surrender the Fleece: to yoke fire-breathing bulls, plough a field, sow it with dragon's teeth, and defeat the warriors that sprang up. Aeetes's daughter Medea, a sorceress, fell in love with Jason and gave him an ointment that protected him from fire. Jason completed the tasks. Aeetes refused his bargain, and Medea drugged the dragon to sleep so Jason could seize the Fleece. They fled together with Aeetes in pursuit, and Medea, in a terrible act, killed her own brother Apsyrtus and scattered his body in the sea so that her father would have to stop and gather the pieces. They returned to Iolcus with the Fleece - but the price of victory, in Medea, was a curse that would destroy them both.",
        'sources' => "Apollonius of Rhodes, Argonautica (full epic)\nApollodorus, Bibliotheca 1.9.16-1.9.27\nPindar, Pythian 4 (the Argonauts at Colchis)\nEuripides, Medea 1-48\nHyginus, Fabulae 14, 22-26",
    ],
    'bellerophon-and-the-chimera' => [
        'text' => "Bellerophon was a young hero of Corinth, a guest at the palace of King Proetus of Tiryns. The king's wife Stheneboea (or Anteia, in Homer) tried to seduce him; when he refused, she accused him to her husband of attempted assault. Proetus, unwilling to break the laws of guest-friendship by killing him directly, sent Bellerophon east to the court of his father-in-law King Iobates of Lycia, bearing a sealed letter that requested the bearer be put to death.\n\nIobates also feared to kill a guest, and so chose to have him killed by a more roundabout means: he sent Bellerophon to slay the Chimera, a monstrous creature with the body of a goat, the front of a lion, and the tail of a serpent, who breathed fire and ravaged the countryside. He was confident the youth would die in the attempt.\n\nBellerophon prayed to Athena and slept in her temple. The goddess came to him in a dream and gave him a golden bridle. With it he was able to capture and tame the winged horse Pegasus, born from the blood of Medusa, who came to drink at the spring of Pirene. From the air, beyond the reach of the Chimera's flames, Bellerophon attacked. He fixed a lump of lead to the tip of his spear and thrust it down the monster's throat; the fiery breath melted the lead, which ran down inside her and killed her. He returned in triumph, but later, in a fit of pride, tried to fly Pegasus up to Olympus itself. Zeus sent a gadfly that stung the horse; Bellerophon was thrown and lived out his days as a lame and broken man, hated by the gods.",
        'sources' => "Homer, Iliad 6.155-202\nHesiod, Theogony 319-325\nApollodorus, Bibliotheca 2.3.1-2.3.2\nPindar, Olympian 13.63-92; Isthmian 7.44\nHyginus, Fabulae 57",
    ],
    'odysseus-and-the-cyclops' => [
        'text' => "Driven by storms after the fall of Troy, Odysseus and his crew of twelve put in at the island of the Cyclopes - savage one-eyed giants who lived without laws or assemblies, each in his own cave with his own flocks. Curious to see what kind of host the place might offer, Odysseus took twelve of his best men and a skin of strong wine and explored the largest cave they found. The Cyclops returned at evening with his sheep, drove them in, and rolled a vast stone across the cave's mouth - a stone no twenty mortal men could have moved.\n\nThe giant - Polyphemus, son of Poseidon - saw the strangers, mocked their plea for hospitality, and seized two of the crew, dashed out their brains against the floor, and ate them raw. He ate two more in the morning before driving out his flock. Odysseus could not simply kill him in his sleep, for then the cave would be sealed forever. He devised a more cunning plan.\n\nHe offered Polyphemus the wine, telling him his name was Outis - 'Nobody.' The Cyclops drank greedily, fell into a stupor, and Odysseus and his men drove a sharpened, fire-hardened stake of olive wood into his single eye. Polyphemus screamed for help, and his neighbours called from outside the cave: 'Who hurts you?' He answered: 'Nobody hurts me!' - and they went away. In the morning, blinded, he opened the cave to let his sheep out, feeling each animal's back to be sure no man rode away. Odysseus had bound his men beneath the bellies of the largest rams, and so they escaped. Once safely aboard ship, Odysseus could not resist shouting his real name. Polyphemus prayed to his father Poseidon for revenge, and the god granted it: Odysseus would lose every companion and not see Ithaca for ten more years.",
        'sources' => "Homer, Odyssey 9.105-566\nApollodorus, Epitome 7.4-7.9\nEuripides, Cyclops (satyr play, full text)\nVirgil, Aeneid 3.616-681\nOvid, Metamorphoses 13.750-869",
    ],
    'the-trojan-horse' => [
        'text' => "After ten years of siege, the Greeks were no closer to taking Troy than they had been at the start. Walls built by Apollo and Poseidon themselves could not be breached by force, and the death of Achilles had robbed the army of its greatest warrior. Then Odysseus, master of cunning, conceived a plan that would end the war by deception rather than arms.\n\nUnder the supervision of the carpenter Epeius, the Greeks built a vast hollow horse of wood. Into its belly climbed a picked band of warriors - Odysseus, Menelaus, Diomedes, Neoptolemus, and others. The rest of the army burned their camp and sailed away, hiding behind the nearby island of Tenedos. They left behind a single Greek, Sinon, with a story to tell: that the horse was an offering to Athena, that the Greeks had given up the war, and that if the Trojans dragged the horse inside their walls they would never fall.\n\nThe Trojans debated. The priest Laocoön cried out, 'I fear Greeks even when they bring gifts,' and hurled his spear at the wooden flank, but two great sea serpents rose from the water and devoured him and his sons. The seer Cassandra warned of doom but, under Apollo's curse, was not believed. The Trojans tore down a section of their own wall to bring the horse inside and feasted long into the night. When the city slept, Sinon opened the horse, the warriors crept out, opened the gates to the returning army, and Troy was put to fire and sword. The greatest city of Asia fell in a single night, by a trick of carpentry.",
        'sources' => "Homer, Odyssey 4.271-289; 8.486-520; 11.523-532\nVirgil, Aeneid 2.13-249 (the fullest narrative)\nApollodorus, Epitome 5.14-5.21\nQuintus Smyrnaeus, Posthomerica 12\nProclus, Chrestomathia (summary of the lost Iliupersis)",
    ],
    'orpheus-in-the-underworld' => [
        'text' => "Orpheus was the son of the Muse Calliope and (in most accounts) the Thracian king Oeagrus, though some traditions name Apollo as his father. He was the greatest of all musicians: when he played the lyre and sang, wild beasts followed him, trees uprooted themselves to come closer, and stones moved aside to let him pass. He sailed with the Argonauts and his music quieted the dreaded Sirens. He took as his bride the dryad Eurydice, and the two were briefly the happiest of mortals.\n\nOn their wedding day Eurydice fled into the meadow from the unwanted advances of the herdsman Aristaeus, was bitten on the heel by a viper, and died. Orpheus's grief was so profound that he resolved to do what no living mortal had done - to descend to Hades himself and bring her back. He passed Cerberus by lulling him with a song. Charon ferried him across the Styx. The shades themselves crowded around to listen. Even the iron-hearted rulers of the dead were moved: Tantalus forgot his thirst, Sisyphus rested on his stone, and the Furies wept tears of iron.\n\nHades and Persephone agreed to release Eurydice on one condition: as Orpheus led her back up to the world of the living, he must not look back at her until both had emerged into the sunlight. He climbed the long dark path before her in silence, listening for her footsteps, fighting the doubt that grew with every step. At the very threshold of the upper world, unable to bear it any longer, he turned. She was still in the dark; she stretched out her arms; with one faint cry of farewell she was drawn back into the underworld forever. Orpheus was not permitted to descend a second time. He wandered grief-stricken through Thrace, was eventually torn apart by Maenads, and his head, still singing, floated down the river Hebrus to the sea.",
        'sources' => "Virgil, Georgics 4.453-527\nOvid, Metamorphoses 10.1-105; 11.1-66\nApollodorus, Bibliotheca 1.3.2\nPlato, Symposium 179d (the alternative tradition)\nPausanias, Description of Greece 9.30",
    ],
    'icarus-and-daedalus' => [
        'text' => "Daedalus, the greatest craftsman of the age, had been summoned to Crete by King Minos to build a hollow wooden cow for Pasiphaë, and afterwards the Labyrinth that imprisoned the Minotaur. When Theseus killed the beast and escaped with Ariadne - having received the thread of guidance from Daedalus himself - Minos was enraged and shut Daedalus and his young son Icarus into the Labyrinth they had built.\n\nDaedalus knew the maze too well to fear it; he could find his way out. The problem was the sea, which Minos's fleet patrolled, and the air, which alone the king did not control. So he gathered feathers - large ones from the wings of seabirds, smaller ones from those of land birds - and arranged them in graduated rows, fastening the bases with linen thread and the rest with wax. With endless patience he built four wings: two for himself, two for his son.\n\nBefore they took flight he warned Icarus carefully. 'Fly the middle course,' he said. 'If you fly too low, the sea spray will weigh down the feathers; if you fly too high, the sun will melt the wax. Stay close to me.' They rose from the cliff together, beating their wings, and the fishermen who looked up to see them passing thought they must be gods. But Icarus, intoxicated with the joy of flight, forgot his father's warning. He climbed higher and higher, and the sun softened the wax until the feathers fell away. He plummeted into the sea and drowned. Daedalus, circling and crying his son's name, found at last only feathers floating on the water, and named that part of the sea Icarian after the boy. He flew on alone to Sicily, where he took refuge with King Cocalus.",
        'sources' => "Ovid, Metamorphoses 8.183-235\nApollodorus, Bibliotheca 3.15.8; Epitome 1.12-1.15\nDiodorus Siculus 4.77\nHyginus, Fabulae 40\nPausanias, Description of Greece 7.4, 9.11",
    ],
    'oedipus-and-the-sphinx' => [
        'text' => "King Laius of Thebes had been warned by an oracle that any son born to him would kill him and marry his mother Jocasta. When their child was born, Laius pierced the infant's ankles, bound them, and gave him to a herdsman to expose on Mount Cithaeron. The herdsman, taking pity, gave the baby to a shepherd from Corinth, who carried him to the childless King Polybus and Queen Merope. They named him Oedipus - 'swollen-foot' - and raised him as their own son.\n\nGrown to manhood and tormented by a rumour that he was not Polybus's true son, Oedipus went to consult the oracle at Delphi, which told him only that he was fated to kill his father and marry his mother. Horrified, and believing this referred to Polybus and Merope, he resolved never to return to Corinth. On the road to Thebes he met an arrogant old man with a small retinue who tried to force him from the road; in the quarrel that followed, Oedipus killed him. The old man was Laius. The first half of the prophecy was fulfilled.\n\nApproaching Thebes, Oedipus came to the rocky pass where the Sphinx - a winged monster sent by Hera to plague the city - devoured every traveller who could not solve her riddle: 'What walks on four legs in the morning, two at noon, and three in the evening?' Oedipus answered: 'A human being, who crawls in infancy, walks upright in maturity, leans on a staff in old age.' The Sphinx, defeated, hurled herself from her cliff and died. The grateful Thebans made Oedipus their king and gave him the recently widowed queen Jocasta - his mother - to marry. The second half of the prophecy was fulfilled, and the great Theban tragedy was set in motion.",
        'sources' => "Sophocles, Oedipus Tyrannus (the central tragedy)\nApollodorus, Bibliotheca 3.5.7-3.5.9\nHesiod, Theogony 326-329 (Sphinx)\nEuripides, Phoenissae 1019-1066\nPausanias, Description of Greece 9.26",
    ],
    'death-of-achilles' => [
        'text' => "When Achilles was an infant his mother Thetis, knowing him fated to die at Troy, sought to make him invulnerable. In one tradition she dipped him in the river Styx, holding him by the heel - so that the heel alone remained mortal. In another she held him over a fire each night to burn away his mortal parts, until Peleus interrupted her and she withdrew in grief. By either telling, the great warrior carried in him a single point of weakness, known only to his mother and the gods.\n\nFor ten years at Troy he was the terror of the Trojans. He killed Hector. He killed the Ethiopian prince Memnon and the Amazon queen Penthesilea. He drove the Trojans back behind their walls again and again. But the gods had set their limit on him. The Iliad tells how he was warned, in his last duel with Hector, that he would not survive much longer; the dying Hector predicted his fall at the Scaean Gate by the hands of Paris and Apollo.\n\nThe death itself is told in poems after Homer. As Achilles fought near the Scaean Gate, Paris - the Trojan prince whose abduction of Helen had begun the war, and who was no warrior at all - drew his bow. Apollo guided the arrow. It struck Achilles in the heel, the one place that could be wounded, and the greatest of the Greeks fell. The Greeks fought a long and bitter battle to recover his body. He was buried with his beloved companion Patroclus on the headland overlooking the Hellespont, where sailors for centuries afterwards would set offerings as they passed.",
        'sources' => "Homer, Iliad 22.355-366 (the prophecy of his death)\nProclus, Chrestomathia (summary of the lost Aethiopis)\nApollodorus, Epitome 5.3-5.5\nQuintus Smyrnaeus, Posthomerica 3\nStatius, Achilleid 1.269-282 (the heel tradition)\nOvid, Metamorphoses 12.580-628",
    ],
    'death-of-hector' => [
        'text' => "When Achilles withdrew from battle in his quarrel with Agamemnon, the Greeks were driven back to their ships. His beloved companion Patroclus, unable to bear the sight, begged for permission to take Achilles's armour and lead the Myrmidons into the fighting. Achilles agreed but warned him to drive the Trojans from the ships and come back. Patroclus, intoxicated with success, pursued the enemy to the very walls of Troy. There Apollo struck him from behind, dazing him; a Trojan wounded him with a spear; and Hector, the great defender of Troy, finished him with a thrust through the belly.\n\nWhen the news reached Achilles, his grief was beyond bearing. He renounced his quarrel with Agamemnon and returned to battle in new armour forged by Hephaestus himself, the shield described in book 18 of the Iliad - perhaps the most famous piece of art in ancient literature. He swept the Trojans before him, choking the river Scamander with corpses, until at last he confronted Hector before the walls of the city.\n\nHector, abandoned at the last by Apollo, fled three times around the walls, but the gods would not allow him to escape his fate. Athena, in disguise, persuaded him to turn and face Achilles. They fought; Achilles drove his spear through the one weak point in the captured armour, the throat above the collarbone, and Hector fell. With his last breath he begged that his body be returned to his father Priam. Achilles refused, lashed the body to his chariot by the heels, and dragged it around the walls of Troy and around Patroclus's funeral pyre. Only when old King Priam came in secret through the Greek camp, guided by Hermes, and embraced Achilles's knees, did Achilles relent and give back the body for burial. The Iliad ends with Hector's funeral.",
        'sources' => "Homer, Iliad 16-24 (the central narrative arc)\nApollodorus, Epitome 4.6-5.1\nVirgil, Aeneid 1.483-487; 2.270-279 (Aeneas's vision)\nQuintus Smyrnaeus, Posthomerica 1.6-32\nDictys Cretensis, Ephemeris belli Trojani 3",
    ],
    'fall-of-troy' => [
        'text' => "Once the Trojan Horse was inside the walls and the city slept, the Greeks emerged from its belly in silence. They opened the gates for the rest of the army, which had returned under cover of darkness from Tenedos. Then began the night that gave its name in Greek tradition to absolute disaster - the Iliupersis, the Sack of Troy.\n\nKing Priam, old and trembling, was cut down at the altar of Zeus in his own courtyard by Neoptolemus, the son of Achilles. His son Polites was killed before his eyes. Cassandra, the prophetess who had foreseen everything, was dragged from the sanctuary of Athena and assaulted by Ajax the Lesser - a sacrilege the goddess would punish on the Greek fleet during the homeward voyage. Hector's wife Andromache was taken as a slave by Neoptolemus; her infant son Astyanax was hurled from the walls. Hecuba, the queen, was given to Odysseus.\n\nNot all the Trojans died. Aeneas, son of Aphrodite and Anchises, escaped through the burning streets carrying his old father on his back and leading his young son Ascanius by the hand, with the household gods of Troy in his arms. He sailed away with a band of survivors, eventually founding a settlement that would become Rome - making the fall of Troy the seed-myth of the Roman people. Helen returned to Menelaus and to Sparta. The Greeks divided the survivors and the spoil and set sail for home. The voyage that should have taken weeks would take years; some never came home at all. The greatest war the Greeks remembered ended not with celebration but with a long and bitter scattering across the seas.",
        'sources' => "Virgil, Aeneid 2 (the fullest narrative)\nHomer, Odyssey 4.271-289; 8.499-520; 11.508-540\nProclus, Chrestomathia (summary of the lost Iliupersis by Arctinus)\nQuintus Smyrnaeus, Posthomerica 13\nApollodorus, Epitome 5.16-5.25\nEuripides, Trojan Women, Hecuba",
    ],
    'apollo-and-daphne' => [
        'text' => "Apollo, fresh from his triumph over the Python at Delphi, mocked the youthful Eros for playing with weapons too great for him. Eros took offence. From his quiver he drew two arrows: one of gold, sharp and gleaming, that kindles love in the heart it strikes; the other of lead, dull and blunt, that drives love away. He shot Apollo with the gold and the nymph Daphne, daughter of the river god Peneus, with the lead.\n\nApollo at once burned with desire for Daphne. She, devoted to Artemis and sworn to lifelong virginity in the wild places, fled from him in horror. He pursued - across meadows, through woods, beside rivers - calling out his name, his lineage, his arts of music and prophecy and healing, all of which were powerless against her dread. Ovid's account of the chase is one of the most beautiful passages in Latin poetry, the god gaining ground with every step until his breath was on her hair.\n\nAt the bank of her father's river, exhausted, she cried out to Peneus to save her by destroying the form that had drawn the god's eye. The transformation began at her feet: roots reached into the earth; bark closed over her body; her arms became branches and her hair leaves. Apollo, embracing the trunk, felt her heart still beating beneath the new bark. He kissed the wood as if it were her cheek. He swore that since she could not be his wife she would forever be his sacred tree, that the laurel would crown his own head, his lyre, his quiver, that every triumphant general and every victor in his Pythian Games would wear a wreath of her leaves. The laurel - daphne in Greek - has carried that meaning ever since.",
        'sources' => "Ovid, Metamorphoses 1.452-567 (the canonical telling)\nHyginus, Fabulae 203\nPausanias, Description of Greece 10.7\nPalaephatus, On Unbelievable Tales 49\nParthenius, Erotica Pathemata 15 (the alternative version)",
    ],
    'judgment-of-paris' => [
        'text' => "At the wedding of the mortal Peleus and the sea goddess Thetis - parents of the future Achilles - every god and goddess had been invited except one: Eris, goddess of strife. Furious at the slight, she came uninvited, and into the assembly of the celebrating gods she rolled a single golden apple inscribed kallistêi - 'for the fairest.' Three goddesses claimed it at once: Hera, queen of the gods; Athena, goddess of wisdom; and Aphrodite, goddess of beauty. The quarrel grew so fierce that Zeus, refusing to choose among his wife, his daughter, and his other daughter, sent the case to a mortal: Paris, prince of Troy, who was at that time tending sheep on the slopes of Mount Ida.\n\nHermes brought the three goddesses to him. Each in turn offered a bribe. Hera promised him sovereignty over all of Asia and great wealth. Athena promised him wisdom and victory in war. Aphrodite, removing her clothing slowly and smiling, promised him the most beautiful woman in the world for his wife. Paris awarded the apple to Aphrodite. Hera and Athena, humiliated, became from that moment the implacable enemies of Troy.\n\nThe most beautiful woman in the world was Helen, queen of Sparta, already married to King Menelaus. Aphrodite kept her promise: when Paris visited Sparta as a guest, the goddess made Helen love him, and they sailed together for Troy. Menelaus called on his brother Agamemnon and on the oath every Greek prince had once sworn to defend Helen's marriage. The fleet that sailed to retrieve her was a thousand ships strong. The Trojan War - a war of ten years, a war that destroyed two civilizations and a generation of heroes - began with a single act of vanity at a wedding feast, and a single boy on a hillside choosing beauty over wisdom and power.",
        'sources' => "Homer, Iliad 24.27-30 (the first reference)\nProclus, Chrestomathia (summary of the lost Cypria)\nEuripides, Trojan Women 924-931; Andromache 274-308\nApollodorus, Epitome 3.2\nHyginus, Fabulae 92\nLucian, Dialogues of the Gods 20",
    ],
    'abduction-of-persephone' => [
        'text' => "Persephone, the only daughter of Demeter and Zeus, was a maiden of unsurpassed beauty. One spring afternoon she was gathering flowers in the meadow of Nysa with her companions - the daughters of Oceanus, Athena and Artemis among them. She wandered apart from the group, drawn to a remarkable narcissus that the earth had grown specifically as a snare. As she reached for it, the ground split open with a tremendous noise, and Hades drove up from the underworld in his chariot drawn by black horses. He seized her, pulled her into the chariot, and plunged back down into the depths before her companions could turn their heads.\n\nDemeter heard her daughter's cry but could not find her. For nine days and nine nights she searched the earth without rest, carrying torches, refusing nectar and ambrosia. On the tenth day Hecate, who had also heard the cry, met her, and Helios the Sun, who sees all, told her what had happened. Her grief turned to a cold and terrible anger. She withdrew from Olympus, took the form of an old woman, and wandered to the village of Eleusis. In her absence the grain stopped growing. The fields lay bare. Famine spread across the world; even sacrifice was failing because there was no grain to offer. The gods themselves grew alarmed.\n\nZeus sent Iris, then every Olympian in turn, to plead with Demeter. She would not relent until her daughter was returned. At last Zeus sent Hermes down to Hades to fetch Persephone back. But Hades, knowing the rule that one who has tasted the food of the dead cannot fully leave the underworld, persuaded Persephone to eat a few seeds of pomegranate before she departed. The compromise that was reached: Persephone would spend a third of the year (the winter months) below with her husband, and the rest above with her mother. Each year, when she descends, Demeter mourns and the earth grows cold; each spring, when she returns, the grain rises and her mother rejoices. The myth was the founding story of the Eleusinian Mysteries, the most sacred initiation rites of the ancient world.",
        'sources' => "Homeric Hymn to Demeter (the canonical telling, full text)\nHesiod, Theogony 912-914\nApollodorus, Bibliotheca 1.5.1-1.5.3\nOvid, Metamorphoses 5.341-571; Fasti 4.417-620\nPausanias, Description of Greece 1.38 (Eleusis)",
    ],
    'europa-and-the-bull' => [
        'text' => "Europa was a princess of Tyre, daughter of King Agenor of Phoenicia. She was renowned for her beauty, and Zeus, looking down from Olympus, fell in love with her. To approach her without alarming her or attracting Hera's notice, the king of the gods took the form of a magnificent white bull and joined the herd of cattle that grazed in the royal pastures.\n\nThe bull was unlike any other. His coat shone like fresh snow, his horns curved like the crescent moon, his breath was sweet as flowers. When Europa came down to the seashore with her companions, the bull approached her gently, lay down in the grass, and offered his back. The other girls were nervous, but Europa stroked his neck and his flanks, hung garlands of flowers on his horns, and at last, laughing, climbed onto his back. The instant she was seated the bull sprang up and ran for the sea. Before her companions could call her back, he was swimming, and the shore was disappearing behind them.\n\nHe carried her across the wine-dark sea to Crete. There, beneath a plane tree near Gortyn, he revealed himself in his true form. Europa bore Zeus three sons: Minos (who became the great king of Crete), Rhadamanthys (a wise lawgiver, later one of the judges of the dead), and Sarpedon (who fought at Troy). She was honoured ever after on Crete and through her marriage to King Asterion gave her name to the continent of Europe - the land toward which Zeus had carried her, away from the Phoenician east.",
        'sources' => "Moschus, Europa (full poem)\nOvid, Metamorphoses 2.836-875; Fasti 5.605-620\nApollodorus, Bibliotheca 3.1.1-3.1.2\nHesiod, Catalogue of Women fr. 140-141 M-W\nHerodotus, Histories 1.2; 4.45 (the rationalising tradition)",
    ],
    'birth-of-aphrodite' => [
        'text' => "When Cronus castrated Uranus and threw the severed parts behind him, they fell into the sea near Cythera. The salt water churned around them, and from the foam (aphros in Greek, the source of her name) a goddess took shape - fully grown, radiantly beautiful, golden-haired. Hesiod's account, the earliest, gives her this miraculous oceanic origin and makes her one of the eldest deities, born before any of the Olympians.\n\nThe waves carried her first to Cythera and then to Cyprus, where she stepped onto the shore. The ground itself bloomed beneath her feet. The Horae - the Seasons - met her on the beach with garments and adornments and led her to Olympus, where every god turned in wonder at her arrival and each, in his turn, hoped to make her his bride.\n\nA later tradition, told most fully by Homer, gives her a different parentage: daughter of Zeus and the Titaness Dione. Both stories were told in antiquity. The Athenian philosopher Plato, in the Symposium, distinguished the two as Aphrodite Urania (the heavenly, born from the sea, presiding over noble love) and Aphrodite Pandemos (the common, daughter of Zeus, presiding over physical desire) - a philosophical reading that the cult never strictly maintained but that has been influential ever since. Whatever her origin, she would become the unstoppable force of attraction in Greek myth, the lover of Ares, the mother of Eros, the patroness of Cyprus and Cythera, and the indirect cause of the Trojan War.",
        'sources' => "Hesiod, Theogony 188-206 (the foam-birth)\nHomer, Iliad 5.370-417 (daughter of Zeus and Dione)\nHomeric Hymn to Aphrodite (5, 6)\nPlato, Symposium 180d-181c (the two Aphrodites)\nPausanias, Description of Greece 1.14, 8.41 (cult of Urania)\nApollodorus, Bibliotheca 1.1.4",
    ],
];

// 3. Apply updates
$ok = 0;
$skipped = 0;
$failed = 0;

foreach ($updates as $slug => $data) {
    $stmt = $conn->prepare("UPDATE myths SET full_text = ?, sources = ? WHERE slug = ?");
    if (!$stmt) {
        echo "[!] Prepare failed for $slug: " . $conn->error . "\n";
        $failed++;
        continue;
    }
    $stmt->bind_param('sss', $data['text'], $data['sources'], $slug);
    if ($stmt->execute()) {
        if ($stmt->affected_rows > 0) {
            echo "[+] Updated $slug\n";
            $ok++;
        } else {
            $check = $conn->prepare("SELECT slug FROM myths WHERE slug = ?");
            $check->bind_param('s', $slug);
            $check->execute();
            $exists = $check->get_result()->num_rows > 0;
            $check->close();
            if ($exists) {
                echo "[=] $slug already up to date\n";
                $ok++;
            } else {
                echo "[?] No row found for $slug - run seed_myths.php first\n";
                $skipped++;
            }
        }
    } else {
        echo "[!] Update failed for $slug: " . $stmt->error . "\n";
        $failed++;
    }
    $stmt->close();
}

$conn->close();

echo "\n----------------------------------------\n";
echo "Done. " . count($updates) . " myths processed.\n";
echo "  Updated: $ok\n";
echo "  Skipped: $skipped\n";
echo "  Failed:  $failed\n";
echo "</pre>";
